# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: dsalvadorjasin@turing.ac.uk
full_name: David Salvador-Jasin
license: MIT
min_python_version: '3.10'
org: alan-turing-institute
project_name: tresa-graph-api
project_short_description: Using the Microsoft Graph API to check active users in
    the Turing's Data Safe Haven
python_name: tresa_graph_api
typing: loose
url: https://github.com/alan-turing-institute/tresa-graph-api
